export type LevelVariant = 'main' | 'alt'

export interface LevelPreset {
  id: string
  title: string
  altTitle: string
}

export const LEVEL_PRESETS: LevelPreset[] = [
  { id: 'level-001', title: 'Синяя Бездна', altTitle: 'Дно' },
  { id: 'level-002', title: 'Demo.*', altTitle: 'Demo*.' },
  { id: 'level-003', title: 'Флеппи Берд', altTitle: 'Змейка' },
  { id: 'level-004', title: 'Майнкрафт', altTitle: 'Разговор' },
  { id: 'level-005', title: 'Город воров', altTitle: 'Сумерка' },
  { id: 'level-006', title: 'Радикалы', altTitle: 'теракт' },
  { id: 'level-007', title: 'Так не честно!', altTitle: 'Лего' },
  { id: 'level-008', title: 'Пустыня блеска', altTitle: 'Морской Бой DLC' },
  { id: 'level-009', title: 'Статика', altTitle: 'Рубикон 2' },
  { id: 'level-010', title: 'Гроб.', altTitle: 'Будущее' },
  { id: 'level-011', title: 'Дедушкин телевизор', altTitle: 'Интернет' },
  { id: 'level-012', title: 'Кладбище', altTitle: 'ПЛОХОЙ КОНЕЦ' },
  { id: 'level-013', title: 'Учебный уровень', altTitle: 'МA(†3Р' },
  { id: 'level-014', title: 'Великие пороки и их последствия: Учение о жизни, труде и смерти', altTitle: 'СОЛАР ПИЗДЕЦ - часть уровня' },
  { id: 'level-015', title: 'Фанатики', altTitle: 'ада все ещё нет...' },
  { id: 'level-016', title: '', altTitle: 'НЕЛЬЗЯ ПОПАСТЬ ПЕРВЫМ' },
  { id: 'level-017', title: 'Интернет', altTitle: 'Дедушкин телевизор' },
  { id: 'level-018', title: 'ОТЕЛЬ', altTitle: 'Каркоза' },
  { id: 'level-019', title: 'Больший мир', altTitle: 'ТОЛЬКО ЧЕРЕЗ ГЕЙТ' },
  { id: 'level-020', title: 'Лабаратория', altTitle: 'Гараж' },
  { id: 'level-021', title: 'Абсолютная жадность', altTitle: 'СЛУЧАЙНЫЙ УРОВЕНЬ' },
  { id: 'level-022', title: 'ДАНННЫХ НЕТ', altTitle: 'Ошибка' },
  { id: 'level-023', title: 'ГОЛОС: ДЕТИ', altTitle: 'Дмитрий Нагиев' },
  { id: 'level-024', title: 'Клуб', altTitle: 'НЕЛЬЗЯ ПОПАСТЬ ПЕРВЫМ' },
  { id: 'level-025', title: 'Пристанище призраков', altTitle: 'Учебный уровень' },
  { id: 'level-026', title: 'Улей', altTitle: 'Заброшенный город' },
  { id: 'level-027', title: 'Город Ветров', altTitle: 'Статика' },
  { id: 'level-028', title: 'Порог', altTitle: 'Пристанище призраков' },
  { id: 'level-029', title: 'Империя Лунтик Сквад', altTitle: 'Башня Романа' },
  { id: 'level-030', title: 'КРИК КРЕАТИВА', altTitle: '' },
  { id: 'level-031', title: 'Общественный туалет', altTitle: 'Так не честно!' },
  { id: 'level-032', title: 'Психолог', altTitle: 'Пациент' },
  { id: 'level-033', title: 'Пациент', altTitle: 'Психолог' },
  { id: 'level-034', title: 'Париж', altTitle: 'И мир лишился красоты' },
  { id: 'level-035', title: 'МA(†3Р', altTitle: 'Ошибка' },
  { id: 'level-036', title: 'Пифагоров Мир', altTitle: 'Demo*' },
  { id: 'level-037', title: 'Бегущий отсюда', altTitle: 'Дерево' },
  { id: 'level-038', title: 'Гонки', altTitle: 'Статика' },
  { id: 'level-039', title: 'Вавилонская Библиотека', altTitle: 'Вечеринка' },
  { id: 'level-040', title: 'Злой фермер', altTitle: 'Успех' },
  { id: 'level-041', title: 'Снова в школу', altTitle: 'РЕМОНТ-АПОКЛИПСИС' },
  { id: 'level-042', title: 'Последняя ярмарка', altTitle: 'Дух времени' },
  { id: 'level-043', title: 'Чистота', altTitle: 'ОБНАЖАЕТ СЛЕДУЮЩИЙ УРОВЕНЬ' },
  { id: 'level-044', title: 'Солнце', altTitle: 'Луна' },
  { id: 'level-045', title: 'Калькулятор 2', altTitle: 'Хаб' },
  { id: 'level-046', title: 'Атлант', altTitle: 'Эдем' },
  { id: 'level-047', title: 'Звезды', altTitle: '-∞' },
  { id: 'level-048', title: 'СОЛАР ПИЗДЕЦ', altTitle: 'КОНТЕНТ НГ+' },
  { id: 'level-049', title: 'Пайдократия', altTitle: 'Воспоминания' },
  { id: 'level-050', title: 'Анимация', altTitle: 'Комната Аниматора' },
  { id: 'level-051', title: 'Пекарня', altTitle: 'Зал' },
  { id: 'level-052', title: 'Зал💪', altTitle: 'Пекарня' },
  { id: 'level-053', title: 'Буквально', altTitle: 'Зал' },
  { id: 'level-054', title: 'Награда', altTitle: 'Успех' },
  { id: 'level-055', title: 'Зараждающаяся вселенная', altTitle: '∞' },
  { id: 'level-056', title: 'Рабство', altTitle: 'Голубая кровь' },
  { id: 'level-057', title: 'Страна лилипутов', altTitle: 'Больший мир' },
  { id: 'level-058', title: 'Поля Иалу', altTitle: 'И мир лишился красоты' },
  { id: 'level-059', title: 'Комбинация', altTitle: 'СОЕДЕНЯЕТ ДВА СЛЕДУЮЩИХ УРОВНЯ' },
  { id: 'level-060', title: 'Метро', altTitle: 'Заброшенная ветка' },
  { id: 'level-061', title: 'Рубикон 2', altTitle: 'ОТКРЫТЫЙ КОСМОС' },
  { id: 'level-062', title: 'Мир Уток', altTitle: 'Империя Гусей' },
  { id: 'level-063', title: 'Блю Люк', altTitle: 'Лимбо' },
  { id: 'level-064', title: "Ма'Хабре", altTitle: 'Сломаный завод' },
  { id: 'level-065', title: 'Будущее', altTitle: 'УСКОРЯЕТ ВРЕМЯ СЛЕДУЮЩЕГО УРОВНЯ' },
  { id: 'level-066', title: 'МАШИНА СНОВ', altTitle: 'КИНЬ КУБИК' },
  { id: 'level-067', title: 'БУНКЕР', altTitle: 'Перекресток' },
  { id: 'level-068', title: 'Система пещер', altTitle: 'Город Ветров' },
  { id: 'level-069', title: 'Шея Атланта', altTitle: 'НЕТ АЛЬТЕРНАТИВЫ' },
  { id: 'level-070', title: 'Дурка', altTitle: 'НЕ АДОЛЬФОВ ПРОПАНЧИКОВ' },
  { id: 'level-071', title: 'ХАБ', altTitle: 'Wolf at the door' },
  { id: 'level-072', title: 'Альтернатива', altTitle: 'Рикиторий' },
  { id: 'level-073', title: 'РОЗА_ДОЖДЕЙ.ЕХЕ', altTitle: 'Ошибка' },
  { id: 'level-074', title: 'Броуновское движение', altTitle: 'Статика' },
  { id: 'level-075', title: 'Э С Т Е Т И К А', altTitle: 'Альтернатива' },
  { id: 'level-076', title: 'Несправедливость', altTitle: 'Убийцы' },
  { id: 'level-077', title: 'Чистые Бассейны', altTitle: 'Синяя Бездна' },
  { id: 'level-078', title: 'Убийцы', altTitle: 'ХАБ' },
  { id: 'level-079', title: 'ОСТРОВ', altTitle: 'НЕТ АЛЬТЕРНАТИВЫ' },
  { id: 'level-080', title: 'Майндбрейк', altTitle: 'МОЖНО ПОПАСТЬ ТОЛЬКО ВО 2 РАЗ' },
  { id: 'level-081', title: 'Happy Satan', altTitle: 'ОТЕЛЬ' },
  { id: 'level-082', title: 'ТЦ: Тревожный цикл', altTitle: 'Иккея' },
  { id: 'level-083', title: 'Танец рыцарей', altTitle: 'Посденяя ярмарка' },
  { id: 'level-084', title: 'ЯПИЯПИЯПИ', altTitle: 'Вызженный мир' },
  { id: 'level-085', title: 'Дух времени', altTitle: 'Последняя ярмарка' },
  { id: 'level-086', title: 'Моя Дурацкая Академия (МДА)', altTitle: 'ЛБХ: Литтлл Баттл Хирмиаут' },
  { id: 'level-087', title: 'Тихий запад', altTitle: 'Статика' },
  { id: 'level-088', title: 'Рикиторий', altTitle: 'Альтернатива' },
  { id: 'level-089', title: 'Корабль захватчика!', altTitle: 'Анапа' },
  { id: 'level-090', title: 'Плейграунд', altTitle: 'Психолог' },
  { id: 'level-091', title: 'ФАНФИКИ', altTitle: 'МОЖНО ПРОПУСТИТЬ' },
  { id: 'level-092', title: 'Поход за Молоком', altTitle: 'Свадьба' },
  { id: 'level-093', title: 'Царь горы', altTitle: 'Рабство' },
  { id: 'level-094', title: 'ДАННЫЕ ЕСТЬ.', altTitle: 'МОЖНО ПОПАСТЬ ТОЛЬКО С ОРИГИНАЛЬНОГО ОБОРУДОВАНИЯ' },
  { id: 'level-095', title: '_Пустое_место_', altTitle: '' },
  { id: 'level-096', title: 'ПОСЛЕЖИЗНЬ', altTitle: '∞' },
  { id: 'level-097', title: 'Каркоза', altTitle: 'НЕТ АЛЬТЕРНАТИВЫ' },
  { id: 'level-098', title: 'Рай 2', altTitle: 'YOU GOT THIS' },
  { id: 'level-099', title: '∞', altTitle: 'НЕЛЬЗЯ ПОПАСТЬ' },
  { id: 'level-100', title: 'Перекресток', altTitle: '' },
]

export function getLevelPreset(id: string | null | undefined): LevelPreset | null {
  if (!id) return null
  return LEVEL_PRESETS.find((level) => level.id === id) ?? null
}
